# Generated by Django 3.2.19 on 2023-05-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0005_alter_journallog_daily_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallog',
            name='daily_rating',
        ),
    ]
