# Generated by Django 3.2.19 on 2023-05-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0006_remove_journallog_daily_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journallog',
            name='featured_image',
        ),
    ]
