# Generated by Django 3.2.19 on 2023-05-23 13:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0007_remove_journallog_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journallog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journallog',
            name='rating',
            field=models.CharField(choices=[('Awful', 'Awful'), ('Bad', 'Bad'), ('Okay', 'Okay'), ('Good', 'Good'), ('Amazing', 'Amazing')], default='Okay', max_length=20),
        ),
    ]
