# Generated by Django 3.2.19 on 2023-05-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0008_auto_20230523_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journallog',
            name='rating',
            field=models.CharField(choices=[('Amazing', 'Amazing'), ('Good', 'Good'), ('Okay', 'Okay'), ('Bad', 'Bad'), ('Awful', 'Awful')], default='Okay', max_length=20),
        ),
    ]
